users:
  name:
    min_length: 6
    max_length: 50
  address:
    min_length: 6
  phone_number:
    min_length: 10
    max_length: 11
vali:
  name:
    min_length: 6
  infomation:
    min_length: 20
per:
  limit_page: 10
  limit_match: 30
